all: newcow reading_cow wildcow tamagochi_cow

newcow: newcow.c
	clang -o newcow newcow.c

reading_cow: reading_cow.c
	clang -o reading_cow reading_cow.c

wildcow: wildcow.c
	clang -o wildcow wildcow.c

tamagochi_cow: tamagochi_cow.c
	clang -o tamagochi_cow tamagochi_cow.c